# Site settings
baseurl = "https://ijsucceed.com/"
themesDir = "/themes/"
languageCode = "en-uk"
title = "a Backend Engineer"
theme = "cactus-theme-master"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-99057145-6"
# Disable comments by leaving disqusShortname empty
disqusShortname = "ijsucceed"

[params]
	name = ""
	description = "a blog by Jeremiah Succeed. Learn data and API integeration for modern web application."
	bio = "a Backend Engineer and Web Advocate."
	# Enter optionally your twitter account
	twitter = "ijsucceed"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = "Fresh content"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "a freelance Web developer with interest on data and API integeration. Lover of all good things."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/ijsucceed"
    # facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/ijsucceed"
    # dribble  = "https://www.dribbble.com/"
